# Generated by Django 5.1.6 on 2025-02-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('BookTitle', models.CharField(max_length=255)),
                ('BookAuthor', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('YearOfPublication', models.IntegerField()),
                ('Publisher', models.CharField(max_length=120)),
                ('imageURL', models.URLField()),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=120)),
                ('friends', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('userAID', models.BigIntegerField()),
                ('userBID', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=4)),
                ('sign', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True)),
                ('signupDate', models.DateField(auto_now_add=True)),
                ('avatar_path', models.FilePathField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenPublish', models.BooleanField(default=True)),
                ('tokenCommunication', models.BooleanField(default=True)),
                ('tokenLogin', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('groupListID', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupList', models.TextField(blank=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField(blank=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('ding', models.IntegerField(default=0)),
                ('numComm', models.IntegerField(default=0)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('replyInformation', models.TextField(blank=True)),
                ('checkStatus', models.BooleanField(default=False)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.admins')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=120)),
                ('isOpen', models.BooleanField(default=True)),
                ('bookList', models.TextField(blank=True)),
                ('numOfBooks', models.BigIntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ForumID', models.BigIntegerField()),
                ('comment', models.CharField(max_length=400)),
                ('objectID', models.BigIntegerField(blank=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('bookListId', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('bookList', models.TextField(blank=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookRecommendationSys.user')),
            ],
        ),
    ]
