# Generated by Django 5.1.6 on 2025-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecommendationSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='fans',
            field=models.IntegerField(default=0),
        ),
    ]
