# Generated by Django 5.1.6 on 2025-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecommendationSys', '0002_booklist_fans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
